name: Claude Phase Builder
on:
  workflow_dispatch:
    inputs:
      forcePhase:
        description: 'Phase number (optional override)'
        required: false
  schedule:
    - cron: '0 6 * * *' # 09:00 Asia/Riyadh (UTC+3)
permissions:
  contents: write
  pull-requests: write
concurrency:
  group: claude-phase
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Run Claude Phase
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          FORCE_PHASE: ${{ inputs.forcePhase }}
        run: node scripts/claude_phase.mjs
